version: "3"
services:
  db:
    image: mariadb:10.5
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=MysqlRootPassword
      - MYSQL_DATABASE=spip
      - MYSQL_USER=spip
      - MYSQL_PASSWORD=spip

  app:
    image: ipeos/spip:4.1
    restart: always
    links:
      - db:mysql
    environment:
      - SPIP_AUTO_INSTALL=1
      - SPIP_DB_SERVER=mysql
      - SPIP_DB_LOGIN=spip
      - SPIP_DB_PASS=spip
      - SPIP_DB_NAME=spip
    ports:
      - 8880:80
